CREATE SCHEMA dictionaries;

CREATE TABLE dictionaries.gender (
    gender_no integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gender varchar NOT NULL
    );
INSERT INTO dictionaries.gender (gender) 
    VALUES ('Male'),('Female'),('Other'),('Anonymous');  

CREATE TABLE dictionaries.roles (
    role_no integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role varchar NOT NULL,
    description varchar NOT NULL
    );
INSERT INTO dictionaries.roles (role,description) 
    VALUES ('Superadmin','Ability to directly modify database'),('Admin','Limited ability to modify database'),('Authorizer','Can approve data entries from Enterer role'),('Enterer','Can enter data into the database'),('Person','Has no stated privileges');

CREATE TABLE dictionaries.countries (
    country_no integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    abbreviation varchar NOT NULL,
    full_name varchar NOT NULL
    );
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(1, 'AF', 'Afghanistan') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(2, 'AX', 'Oland Islands') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(3, 'AL', 'Albania') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(4, 'DZ', 'Algeria') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(5, 'AS', 'American Samoa') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(6, 'AD', 'Andorra') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(7, 'AO', 'Angola') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(8, 'AI', 'Anguilla') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(9, 'AQ', 'Antarctica') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(10, 'AG', 'Antigua and Barbuda') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(11, 'AR', 'Argentina') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(12, 'AM', 'Armenia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(13, 'AW', 'Aruba') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(14, 'AU', 'Australia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(15, 'AT', 'Austria') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(16, 'AZ', 'Azerbaijan') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(17, 'BS', 'Bahamas') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(18, 'BH', 'Bahrain') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(19, 'BD', 'Bangladesh') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(20, 'BB', 'Barbados') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(21, 'BY', 'Belarus') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(22, 'BE', 'Belgium') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(23, 'BZ', 'Belize') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(24, 'BJ', 'Benin') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(25, 'BM', 'Bermuda') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(26, 'BT', 'Bhutan') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(27, 'BO', 'Bolivia, Plurinational State of') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(28, 'BQ', 'Bonaire, Sint Eustatius and Saba') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(29, 'BA', 'Bosnia and Herzegovina') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(30, 'BW', 'Botswana') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(31, 'BV', 'Bouvet Island') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(32, 'BR', 'Brazil') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(33, 'IO', 'British Indian Ocean Territory') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(34, 'BN', 'Brunei Darussalam') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(35, 'BG', 'Bulgaria') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(36, 'BF', 'Burkina Faso') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(37, 'BI', 'Burundi') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(38, 'KH', 'Cambodia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(39, 'CM', 'Cameroon') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(40, 'CA', 'Canada') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(41, 'CV', 'Cape Verde') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(42, 'KY', 'Cayman Islands') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(43, 'CF', 'Central African Republic') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(44, 'TD', 'Chad') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(45, 'CL', 'Chile') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(46, 'CN', 'China') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(47, 'CX', 'Christmas Island') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(48, 'CC', 'Cocos (Keeling) Islands') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(49, 'CO', 'Colombia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(50, 'KM', 'Comoros') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(51, 'CG', 'Congo') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(52, 'CD', 'Congo, the Democratic Republic of the') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(53, 'CK', 'Cook Islands') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(54, 'CR', 'Costa Rica') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(55, 'CI', 'C√¥te d''Ivoire') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(56, 'HR', 'Croatia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(57, 'CU', 'Cuba') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(58, 'CW', 'Cura√ßao') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(59, 'CY', 'Cyprus') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(60, 'CZ', 'Czech Republic') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(61, 'DK', 'Denmark') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(62, 'DJ', 'Djibouti') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(63, 'DM', 'Dominica') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(64, 'DO', 'Dominican Republic') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(65, 'EC', 'Ecuador') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(66, 'EG', 'Egypt') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(67, 'SV', 'El Salvador') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(68, 'GQ', 'Equatorial Guinea') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(69, 'ER', 'Eritrea') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(70, 'EE', 'Estonia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(71, 'ET', 'Ethiopia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(72, 'FK', 'Falkland Islands (Malvinas)') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(73, 'FO', 'Faroe Islands') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(74, 'FJ', 'Fiji') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(75, 'FI', 'Finland') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(76, 'FR', 'France') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(77, 'GF', 'French Guiana') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(78, 'PF', 'French Polynesia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(79, 'TF', 'French Southern Territories') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(80, 'GA', 'Gabon') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(81, 'GM', 'Gambia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(82, 'GE', 'Georgia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(83, 'DE', 'Germany') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(84, 'GH', 'Ghana') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(85, 'GI', 'Gibraltar') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(86, 'GR', 'Greece') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(87, 'GL', 'Greenland') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(88, 'GD', 'Grenada') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(89, 'GP', 'Guadeloupe') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(90, 'GU', 'Guam') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(91, 'GT', 'Guatemala') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(92, 'GG', 'Guernsey') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(93, 'GN', 'Guinea') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(94, 'GW', 'Guinea-Bissau') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(95, 'GY', 'Guyana') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(96, 'HT', 'Haiti') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(97, 'HM', 'Heard Island and McDonald Islands') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(98, 'VA', 'Holy See (Vatican City State)') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(99, 'HN', 'Honduras') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(100, 'HK', 'Hong Kong') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(101, 'HU', 'Hungary') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(102, 'IS', 'Iceland') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(103, 'IN', 'India') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(104, 'ID', 'Indonesia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(105, 'IR', 'Iran, Islamic Republic of') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(106, 'IQ', 'Iraq') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(107, 'IE', 'Ireland') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(108, 'IM', 'Isle of Man') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(109, 'IL', 'Israel') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(110, 'IT', 'Italy') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(111, 'JM', 'Jamaica') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(112, 'JP', 'Japan') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(113, 'JE', 'Jersey') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(114, 'JO', 'Jordan') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(115, 'KZ', 'Kazakhstan') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(116, 'KE', 'Kenya') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(117, 'KI', 'Kiribati') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(118, 'KP', 'Korea, Democratic People''s Republic of') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(119, 'KR', 'Korea, Republic of') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(120, 'KW', 'Kuwait') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(121, 'KG', 'Kyrgyzstan') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(122, 'LA', 'Lao People''s Democratic Republic') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(123, 'LV', 'Latvia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(124, 'LB', 'Lebanon') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(125, 'LS', 'Lesotho') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(126, 'LR', 'Liberia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(127, 'LY', 'Libya') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(128, 'LI', 'Liechtenstein') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(129, 'LT', 'Lithuania') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(130, 'LU', 'Luxembourg') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(131, 'MO', 'Macao') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(132, 'MK', 'Macedonia, the Former Yugoslav Republic of') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(133, 'MG', 'Madagascar') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(134, 'MW', 'Malawi') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(135, 'MY', 'Malaysia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(136, 'MV', 'Maldives') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(137, 'ML', 'Mali') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(138, 'MT', 'Malta') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(139, 'MH', 'Marshall Islands') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(140, 'MQ', 'Martinique') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(141, 'MR', 'Mauritania') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(142, 'MU', 'Mauritius') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(143, 'YT', 'Mayotte') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(144, 'MX', 'Mexico') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(145, 'FM', 'Micronesia, Federated States of') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(146, 'MD', 'Moldova, Republic of') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(147, 'MC', 'Monaco') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(148, 'MN', 'Mongolia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(149, 'ME', 'Montenegro') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(150, 'MS', 'Montserrat') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(151, 'MA', 'Morocco') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(152, 'MZ', 'Mozambique') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(153, 'MM', 'Myanmar') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(154, 'NA', 'Namibia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(155, 'NR', 'Nauru') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(156, 'NP', 'Nepal') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(157, 'NL', 'Netherlands') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(158, 'NC', 'New Caledonia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(159, 'NZ', 'New Zealand') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(160, 'NI', 'Nicaragua') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(161, 'NE', 'Niger') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(162, 'NG', 'Nigeria') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(163, 'NU', 'Niue') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(164, 'NF', 'Norfolk Island') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(165, 'MP', 'Northern Mariana Islands') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(166, 'NO', 'Norway') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(167, 'OM', 'Oman') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(168, 'PK', 'Pakistan') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(169, 'PW', 'Palau') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(170, 'PS', 'Palestine, State of') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(171, 'PA', 'Panama') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(172, 'PG', 'Papua New Guinea') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(173, 'PY', 'Paraguay') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(174, 'PE', 'Peru') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(175, 'PH', 'Philippines') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(176, 'PN', 'Pitcairn') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(177, 'PL', 'Poland') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(178, 'PT', 'Portugal') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(179, 'PR', 'Puerto Rico') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(180, 'QA', 'Qatar') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(181, 'RE', 'Reunion') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(182, 'RO', 'Romania') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(183, 'RU', 'Russian Federation') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(184, 'RW', 'Rwanda') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(185, 'BL', 'Saint Barth√©lemy') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(186, 'SH', 'Saint Helena, Ascension and Tristan da Cunha') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(187, 'KN', 'Saint Kitts and Nevis') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(188, 'LC', 'Saint Lucia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(189, 'MF', 'Saint Martin (French part)') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(190, 'PM', 'Saint Pierre and Miquelon') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(191, 'VC', 'Saint Vincent and the Grenadines') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(192, 'WS', 'Samoa') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(193, 'SM', 'San Marino') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(194, 'ST', 'Sao Tome and Principe') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(195, 'SA', 'Saudi Arabia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(196, 'SN', 'Senegal') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(197, 'RS', 'Serbia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(198, 'SC', 'Seychelles') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(199, 'SL', 'Sierra Leone') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(200, 'SG', 'Singapore') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(201, 'SX', 'Sint Maarten (Dutch part)') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(202, 'SK', 'Slovakia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(203, 'SI', 'Slovenia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(204, 'SB', 'Solomon Islands') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(205, 'SO', 'Somalia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(206, 'ZA', 'South Africa') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(207, 'GS', 'South Georgia and the South Sandwich Islands') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(208, 'SS', 'South Sudan') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(209, 'ES', 'Spain') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(210, 'LK', 'Sri Lanka') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(211, 'SD', 'Sudan') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(212, 'SR', 'Suriname') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(213, 'SJ', 'Svalbard and Jan Mayen') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(214, 'SZ', 'Swaziland') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(215, 'SE', 'Sweden') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(216, 'CH', 'Switzerland') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(217, 'SY', 'Syrian Arab Republic') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(218, 'TW', 'Taiwan, Province of China') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(219, 'TJ', 'Tajikistan') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(220, 'TZ', 'Tanzania, United Republic of') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(221, 'TH', 'Thailand') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(222, 'TL', 'Timor-Leste') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(223, 'TG', 'Togo') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(224, 'TK', 'Tokelau') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(225, 'TO', 'Tonga') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(226, 'TT', 'Trinidad and Tobago') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(227, 'TN', 'Tunisia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(228, 'TR', 'Turkey') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(229, 'TM', 'Turkmenistan') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(230, 'TC', 'Turks and Caicos Islands') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(231, 'TV', 'Tuvalu') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(232, 'UG', 'Uganda') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(233, 'UA', 'Ukraine') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(234, 'AE', 'United Arab Emirates') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(235, 'GB', 'United Kingdom') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(236, 'US', 'United States') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(237, 'UM', 'United States Minor Outlying Islands') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(238, 'UY', 'Uruguay') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(239, 'UZ', 'Uzbekistan') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(240, 'VU', 'Vanuatu') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(241, 'VE', 'Venezuela, Bolivarian Republic of') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(242, 'VN', 'Viet Nam') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(243, 'VG', 'Virgin Islands, British') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(244, 'VI', 'Virgin Islands, U.S.') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(245, 'WF', 'Wallis and Futuna') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(246, 'EH', 'Western Sahara') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(247, 'YE', 'Yemen') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(248, 'ZM', 'Zambia') RETURNING "country_no", "abbreviation", "full_name";
INSERT INTO "dictionaries"."countries"("country_no", "abbreviation", "full_name") VALUES(249, 'ZW', 'Zimbabwe') RETURNING "country_no", "abbreviation", "full_name";

CREATE TABLE dictionaries.taxonomy_rank (
    taxononmy_rank_no integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taxonomy_rank varchar NOT NULL
    );
INSERT INTO dictionaries.taxonomy_rank (taxonomy_rank) 
    VALUES ('subspecies'),('species'),('subgenus'),('genus'),('subtribe'),('tribe'),('subfamily'),('family'),('superfamily'),('infraorder'),('suborder'),('superorder'),('infraclass'),('subclass'),('class'),('superclass'),('subphylum'),('phylum'),('superphylum'),('subkingdom'),('kingdom'),('superkingdom'),('unranked clade'),('unranked');

CREATE TABLE dictionaries.refs_types (
    refs_type_no integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refs_type varchar
    );
INSERT INTO dictionaries.refs_types (refs_type) 
    VALUES ('journal article'),('standalone book'),('edited book of contributed articles'),('contributed article in edited book'),('unpublished');

CREATE TABLE dictionaries.taxonomy_relationship (
    taxonomy_relationship_no integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taxonomy_relationship varchar
    );
INSERT INTO dictionaries.taxonomy_relationship (taxonomy_relationship)
    VALUES ('belongs to'),('subjective synonym of'),('objective synonym of'),('invalid subgroup of'),('misspelling of'),('replaced by'),('nomen dubium'),('nomen nudum'),('nomen oblitum'),('nomen vanum');

CREATE TABLE dictionaries.taxonomy_confidence (
    taxonomy_confidence_no integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taxonomy_confidence varchar,
    taxonomy_confidence_definition varchar
    );
INSERT INTO dictionaries.taxonomy_confidence (taxonomy_confidence,taxonomy_confidence_definition)
    VALUES ('accepted','An accepted name is a valid name that is not a junior synonym.'),('superseded','A valid name that is a junior synonym.'),('operational','An informal name that can confidently be used as an operational taxonomic unit.'),('tentative','An informal name that is not recommended for general use as an operational taxonomic unit.'),('invalid','A name that is formally considered invalid.');

CREATE TABLE person (
    person_no integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    given varchar NOT NULL,
    surname varchar NOT NULL,
    middle varchar,
    email varchar,
    password varchar,
    orcid varchar,
    role_no integer REFERENCES dictionaries.roles("role_no") NOT NULL,
    role_parent integer REFERENCES dictionaries.roles("role_no"),
    gender_no integer REFERENCES dictionaries.gender("gender_no") NOT NULL,
    country_no integer REFERENCES dictionaries.countries("country_no") NOT NULL,
    institution varchar,
    active boolean,
    total_hours numeric
    );
    
 CREATE TABLE refs (
     refs_vers integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     refs_no integer NOT NULL, -- This is a permanent id that will stay constant regardless of version
     refs_type_no integer REFERENCES dictionaries.refs_types("refs_type_no"),
     authorizer_no integer REFERENCES person("person_no") NOT NULL, -- Whoever was the authorizer of the enterer
     enterer_no integer REFERENCES person("person_no") NOT NULL, -- Whoever made the entry or edit
     ref_json jsonb, -- references JSON PBot node
     preceded_by integer REFERENCES refs("refs_vers"),
     succeeded_by integer REFERENCES refs("refs_vers"),
     removed boolean
     );

 CREATE TABLE collections (
     collection_vers integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     collection_no integer NOT NULL, -- This is a permanent id that will stay constant regardless of version
     authorizer_no integer REFERENCES person("person_no") NOT NULL, -- Whoever was the authorizer of the enterer
     enterer_no integer REFERENCES person("person_no") NOT NULL, -- Whoever made the entry or edit
     collection_json jsonb, -- Collection json -- taken directly from PBot!!!
     refs_no integer NOT NULL, -- A single refs is considered the "primary". 
     preceded_by integer REFERENCES collections("collection_vers"),
     succeeded_by integer REFERENCES collections("collection_vers"),
     removed boolean
     );

-- A lookup table for additional refs (called refs_secondary in original db)
CREATE TABLE refs_additional (
    refs_additional_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_no integer REFERENCES collections("collection_no"),
    refs_no integer REFERENCES refs("refs_no")
    );

-- The opinion system in PBDB is one of its most important and unique components
-- We need to preserve all of its current functionality while also introducing
-- Some more flexibility for PBot, namely the inclusion of more types of
-- taxonomic_relatiobnship 
CREATE TABLE opinion (
    opinion_no integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authorizer_no integer REFERENCES person("person_no") NOT NULL, -- Whoever was the authorizer of the enterer
    enterer_no integer REFERENCES person("person_no") NOT NULL, -- Whoever made the entry or edit
    refs_no integer REFERENCES refs("refs_no") NOT NULL,
    related_taxon_no integer REFERENCES taxon("taxon_no") NOT NULL,
    taxonomy_relationship_no integer REFERENCES dictionaries.taxonomy_relationship("taxonomy_relationship_no"),
    preceded_by integer REFERENCES opinion("collection_vers"),
    succeeded_by integer REFERENCES opinion("collection_vers")
    );

-- I am positing here a complete rework of the taxon table in that it only exists 
-- as a derived outcome based on logical analysis of the opinion table
-- therefore no user ever adds a new taxon, they only ever add a new opinion
-- from which we derive the existence of the taxon
CREATE TABLE taxon (
    taxon_no integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taxonomy_confidence integer REFERENCES dictionaries.taxonomy_confidence("taxonomy_confidence_no"),
    taxononmy_rank_no integer REFERENCES dictionaries.taxonomy_confidence("taxonomy_rank_no")
    );

